### ISSUE TITLE
SemVer violation in crate version 0.3.1

### ISSUE THREAD

**Issue by p-e-w** [syvb/wikidata#4]
`wikidata` version 0.3.1, published on 2023-11-11, adds

```rust
#[non_exhaustive]
```

to the `WikiId` enum. This is a breaking change, for which Cargo's SemVer semantics demand a minor version bump for pre-1.0 crates. Publishing this change in a patch version, as has happened, breaks any dependent crate which does pattern matching on that enum (see https://github.com/p-e-w/wd2sql/issues/12 for an example).

I recommend yanking crate version 0.3.1, and republishing it as 0.4.0.

**Comment by syvb** [comment]
Sorry about that, I thought I had already published the `#[non_exhaustive]` changes in 0.3.0.

I yanked 0.3.1, and published 1.0.0.

**Comment by p-e-w** [comment]
Thanks!
