### ISSUE TITLE
Allow for fetching a specific claim from an Entity

### ISSUE THREAD

**Issue by Susurrus** [syvb/wikidata#6]
I'm trying to use your library to extract specific values from items. So I have a list of known claims that I want. Right now I need to iterate through all the claims and match on any that I want. So this is iterating through `Entity.claims` and then comparing it to a list of attributes on my end. It'd be nicer if I could lookup claims directly by using them as an index into a map. I'm not certain if the order of claims matters, I assume it doesn't for triple-stores/Wikidata, but even if so, an ordered map could be used.

**Comment by Susurrus** [comment]
Same thing applies to `ClaimValue.qualifiers`. I'm trying to fetch just the Name qualifiers, but I have to iterate through and find it.

**Comment by syvb** [comment]
I added some helper functions in #7 - would those solve your problem?
